"""The canonicalizer must be byte-identical to SiloBench's, proven by the
committed cross-language vectors (generated by the TypeScript implementation),
not only by the all-ASCII baseline snapshots."""

import pytest

from statediff.canonical import CanonicalError, canonical_json, sha256_hex, strict_equal
from tests.conftest import FIXTURES, read_json

VECTORS = read_json(FIXTURES / "vectors" / "canonical-vectors.json")


def test_vector_file_shape():
    assert VECTORS["format"] == "canonical-vectors.v1"
    assert len(VECTORS["vectors"]) >= 8


@pytest.mark.parametrize("vector", VECTORS["vectors"], ids=lambda v: v["name"])
def test_canonical_matches_reference_implementation(vector):
    canonical = canonical_json(vector["doc"])
    assert canonical == vector["canonical"]
    assert sha256_hex(canonical) == vector["sha256"]


def test_floats_are_rejected():
    with pytest.raises(CanonicalError):
        canonical_json({"x": 1.5})


def test_booleans_are_not_integers():
    assert canonical_json({"t": True, "one": 1}) == '{"one":1,"t":true}'


def test_strict_equal_separates_booleans_integers_and_floats():
    # Python calls all three of these equal. Canonical JSON writes them three
    # different ways, so any comparison feeding a verdict has to disagree with
    # Python: `210000` and `210000.0` are not the same exported number, and a
    # comparison that says they are lets two artifacts that differ be reported
    # as reconciled.
    assert strict_equal(1, 1)
    assert strict_equal(1.0, 1.0)
    assert not strict_equal(1, True)
    assert not strict_equal(210000, 210000.0)
    assert not strict_equal({"amount_cents": 210000}, {"amount_cents": 210000.0})
    assert not strict_equal([210000], [210000.0])
